add_lunch_combo Droid_Concepts_toro-user
add_lunch_combo Droid_Concepts_toro-userdebug
add_lunch_combo Droid_Concepts_maguro-user
add_lunch_combo Droid_Concepts_maguro-userdebug
add_lunch_combo Droid_Concepts_mako-user
add_lunch_combo Droid_Concepts_mako-userdebug
