#!/system/bin/sh
# cphelps76
#

LOG_FILE=/data/dementedgov.log

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

# Governor Tweaks
#
#ondemand
#echo "70" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
#echo "40000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
#echo "2" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
#echo "15" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential

#conservative
#echo "60" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
#echo "40000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate
#echo "5" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
#echo "20" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
#echo "25" > /sys/devices/system/cpu/cpufreq/conservative/freq_step

#interactive
echo "95" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
echo "1000000" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
echo "10000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate


#Hot Plug Persistent
#
#echo "1" > /sys/module/dsscomp/parameters/hotplug_enabled

