#!/system/bin/sh
# cphelps76

LOG_FILE=/data/dementedkernel.log

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

# Kernel Tweaks
#
sysctl -w kernel.panic=0
sysctl -w kernel.panic_on_oops=1
sysctl -w kernel.msgmni=2048
sysctl -w kernel.msgmax=64000
sysctl -w kernel.shmmax=268435500
sysctl -w kernel.sem=500,512000,64,2048
sysctl -w kernel.hung_task_timeout_secs=0
sysctl -w kernel.sched_latency_ns=5000000; #600000
sysctl -w kernel.sched_min_granularity_ns=1000000; #400000
sysctl -w kernel.sched_wakeup_granularity_ns=1000000
sysctl -w kernel.sched_child_runs_first=0
sysctl -w kernel.threads-max=525810

# disable logger - (comment and reboot for logcat)
# rm /dev/log/main
