#!/system/bin/sh
#

LOG_FILE=/data/dementedkernel.log

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

# Kernel Tweaks
#
sysctl -w kernel.sched_features=15834233
sysctl -w kernel.panic=0
sysctl -w kernel.panic_on_oops=1
sysctl -w kernel.msgmni=2048
sysctl -w kernel.msgmax=64000
sysctl -w kernel.shmmax=268435500
sysctl -w kernel.sem=500,512000,64,2048
sysctl -w kernel.hung_task_timeout_secs=0
sysctl -w kernel.sched_latency_ns=5000000; #600000
sysctl -w kernel.sched_min_granularity_ns=1000000; #400000
sysctl -w kernel.sched_wakeup_granularity_ns=1000000
sysctl -w kernel.sched_compat_yield=1
sysctl -w kernel.sched_shares_ratelimit=256000
sysctl -w kernel.sched_child_runs_first=0
sysctl -w kernel.threads-max=525810
sysctl -w kernel.multi_threading=2

# disable logger - (comment and reboot for logcat)
# rm /dev/log/main

#I/O
#
echo "0 0 0 1 1 1 2 2" > /sys/devices/system/cpu/cpu0/cpufreq/busfreq_static
echo "enabled" > /sys/devices/system/cpu/cpu0/cpufreq/busfreq_static
echo "noop" > /sys/block/mmcblk0/queue/scheduler

#Core/Freq/Bus
#
echo "3" > /sys/module/cpuidle/parameters/enable_mask
echo "5" > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_cpulevel
echo "2" > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_buslevel

#Scaling
#
echo "1" > /sys/devices/system/cpu/sched_mc_power_savings
echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_target
echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_offset
echo "0" > /sys/devices/system/cpu/cpu0/cpufreq/smooth_step

