# Beats Audio
PRODUCT_COPY_FILES += \
    vendor/Droid_Concepts/proprietary/common/beats/app/AudioEffectService.apk:system/app/AudioEffectService.apk \
    vendor/Droid_Concepts/proprietary/common/beats/app/DCBeats.apk:system/app/DCBeats.apk \
    vendor/Droid_Concepts/proprietary/common/beats/bin/basimage_gec.bin:system/bin/basimage_gec.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/basimage_gec_x.bin:system/bin/basimage_gec_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/basimage_ibeats.bin:system/bin/basimage_ibeats.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/basimage_ibeats_solo.bin:system/bin/basimage_ibeats_solo.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/basimage_ibeats_solo_x.bin:system/bin/basimage_ibeats_solo_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/basimage_ibeats_x.bin:system/bin/basimage_ibeats_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/dynimage_gec.bin:system/bin/dynimage_gec.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/dynimage_gec_x.bin:system/bin/dynimage_gec_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/dynimage_ibeats.bin:system/bin/dynimage_ibeats.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/dynimage_ibeats_solo.bin:system/bin/dynimage_ibeats_solo.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/dynimage_ibeats_solo_x.bin:system/bin/dynimage_ibeats_solo_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/dynimage_ibeats_x.bin:system/bin/dynimage_ibeats_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/mm-audio-alsa-test:system/bin/mm-audio-alsa-test \
    vendor/Droid_Concepts/proprietary/common/beats/bin/mm-venc-omx-test720p:system/bin/mm-venc-omx-test720p \
    vendor/Droid_Concepts/proprietary/common/beats/bin/mm-video-encdrv-test:system/bin/mm-video-encdrv-test \
    vendor/Droid_Concepts/proprietary/common/beats/bin/peqimage_gec.bin:system/bin/peqimage_gec.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/peqimage_gec.bin:system/bin/peqimage_gec.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/peqimage_gec_x.bin:system/bin/peqimage_gec_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/peqimage_ibeats.bin:system/bin/peqimage_ibeats.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/peqimage_ibeats_solo.bin:system/bin/peqimage_ibeats_solo.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/peqimage_ibeats_solo_x.bin:system/bin/peqimage_ibeats_solo_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/peqimage_ibeats_x.bin:system/bin/peqimage_ibeats_x.bin \
    vendor/Droid_Concepts/proprietary/common/beats/bin/snd:system/bin/snd \
    vendor/Droid_Concepts/proprietary/common/beats/bin/snd8k:system/bin/snd8k \
    vendor/Droid_Concepts/proprietary/common/beats/bin/sound:system/bin/sound \
    vendor/Droid_Concepts/proprietary/common/beats/bin/sound8x60:system/bin/sound8x60 \
    vendor/Droid_Concepts/proprietary/common/beats/bin/spkamp:system/bin/spkamp \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/aeqcoe.txt:system/etc/audio/aeqcoe.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/eqfilter.txt:system/etc/audio/eqfilter.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/lmfilter.txt:system/etc/audio/lmfilter.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/situation.txt:system/etc/audio/situation.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/soundbooster.txt:system/etc/audio/soundbooster.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/stream_earpiece.txt:system/etc/audio/stream_earpiece.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/stream_headset.txt:system/etc/audio/stream_headset.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio/stream_speaker.txt:system/etc/audio/stream_speaker.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/Droid_Concepts/proprietary/common/beats/etc/permissions/com.sonyericsson.audioeffectif.xml:system/etc/permissions/com.sonyericsson.audioeffectif.xml \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Bass_Booster.txt:system/etc/soundimage/Sound_Bass_Booster.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Blues.txt:system/etc/soundimage/Sound_Blues.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Classical.txt:system/etc/soundimage/Sound_Classical.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Country.txt:system/etc/soundimage/Sound_Country.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Dolby_A_HP.txt:system/etc/soundimage/Sound_Dolby_A_HP.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Dolby_A_SPK.txt:system/etc/soundimage/Sound_Dolby_A_SPK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Dolby_V_HP.txt:system/etc/soundimage/Sound_Dolby_V_HP.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Dolby_V_SPK.txt:system/etc/soundimage/Sound_Dolby_V_SPK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Dualmic.txt:system/etc/soundimage/Sound_Dualmic.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Dualmic_EP.txt:system/etc/soundimage/Sound_Dualmic_EP.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Dualmic_SPK.txt:system/etc/soundimage/Sound_Dualmic_SPK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Jazz.txt:system/etc/soundimage/Sound_Jazz.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Latin.txt:system/etc/soundimage/Sound_Latin.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_New_Age.txt:system/etc/soundimage/Sound_New_Age.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Original.txt:system/etc/soundimage/Sound_Original.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Original_BCLK.txt:system/etc/soundimage/Sound_Original_BCLK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Original_Rec_MFG.txt:system/etc/soundimage/Sound_Original_Rec_MFG.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Original_Recording_BCLK.txt:system/etc/soundimage/Sound_Original_Recording_BCLK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Original_SPK_BCLK.txt:system/etc/soundimage/Sound_Original_SPK_BCLK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Original_SPK_MFG.txt:system/etc/soundimage/Sound_Original_SPK_MFG.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Phone_Original_HP_BCLK.txt:system/etc/soundimage/Sound_Phone_Original_HP_BCLK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Phone_Original_HP_WB.txt:system/etc/soundimage/Sound_Phone_Original_HP_WB.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Phone_Original_REC_BCLK.txt:system/etc/soundimage/Sound_Phone_Original_REC_BCLK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Phone_Original_REC_NEL.txt:system/etc/soundimage/Sound_Phone_Original_REC_NEL.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Phone_Original_REC_WB.txt:system/etc/soundimage/Sound_Phone_Original_REC_WB.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Phone_Original_SPK_BCLK.txt:system/etc/soundimage/Sound_Phone_Original_SPK_BCLK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Phone_Original_SPK_WB.txt:system/etc/soundimage/Sound_Phone_Original_SPK_WB.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Piano.txt:system/etc/soundimage/Sound_Piano.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Pop.txt:system/etc/soundimage/Sound_Pop.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_R_B.txt:system/etc/soundimage/Sound_R_B.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Recording_Mono.txt:system/etc/soundimage/Sound_Recording_Mono.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Rock.txt:system/etc/soundimage/Sound_Rock.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_SRS_A_HP.txt:system/etc/soundimage/Sound_SRS_A_HP.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_SRS_A_SPK.txt:system/etc/soundimage/Sound_SRS_A_SPK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_SRS_V_HP.txt:system/etc/soundimage/Sound_SRS_V_HP.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_SRS_V_SPK.txt:system/etc/soundimage/Sound_SRS_V_SPK.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Treble_Booster.txt:system/etc/soundimage/Sound_Treble_Booster.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/Sound_Vocal_Booster.txt:system/etc/soundimage/Sound_Vocal_Booster.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srs_bypass.cfg:system/etc/soundimage/srs_bypass.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srsfx_trumedia_51.cfg:system/etc/soundimage/srsfx_trumedia_51.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srsfx_trumedia_movie.cfg:system/etc/soundimage/srsfx_trumedia_movie.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srsfx_trumedia_music.cfg:system/etc/soundimage/srsfx_trumedia_music.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srsfx_trumedia_music_wide.cfg:system/etc/soundimage/srsfx_trumedia_music_wide.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srsfx_trumedia_voice.cfg:system/etc/soundimage/srsfx_trumedia_voice.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srs_geq10.cfg:system/etc/soundimage/srs_geq10.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/soundimage/srs_global.cfg:system/etc/soundimage/srs_global.cfg \
    vendor/Droid_Concepts/proprietary/common/beats/etc/AdieHWCodec.csv:system/etc/AdieHWCodec.csv \
    vendor/Droid_Concepts/proprietary/common/beats/etc/AdieHWCodec_BEATS_HW.csv:system/etc/AdieHWCodec_BEATS_HW.csv \
    vendor/Droid_Concepts/proprietary/common/beats/etc/AIC3254_REG.csv:system/etc/AIC3254_REG.csv \
    vendor/Droid_Concepts/proprietary/common/beats/etc/AIC3254_REG_DualMic.csv:system/etc/AIC3254_REG_DualMic.csv \
    vendor/Droid_Concepts/proprietary/common/beats/etc/AIC3254_REG_XD.csv:system/etc/AIC3254_REG_XD.csv \
    vendor/Droid_Concepts/proprietary/common/beats/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/Droid_Concepts/proprietary/common/beats/etc/be_movie:system/etc/be_movie \
    vendor/Droid_Concepts/proprietary/common/beats/etc/be_photo:system/etc/be_photo \
    vendor/Droid_Concepts/proprietary/common/beats/etc/CodecDSPID.txt:system/etc/CodecDSPID.txt \
    vendor/Droid_Concepts/proprietary/common/beats/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/Droid_Concepts/proprietary/common/beats/etc/TPA2051_CFG.csv:system/etc/TPA2051_CFG.csv \
    vendor/Droid_Concepts/proprietary/common/beats/etc/TPA2051_CFG_BEATS_HW.csv:system/etc/TPA2051_CFG_BEATS_HW.csv \
    vendor/Droid_Concepts/proprietary/common/beats/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/Droid_Concepts/proprietary/common/beats/framework/com.srs.fusion.fx.jar:system/framework/com.srs.fusion.fx.jar \
    vendor/Droid_Concepts/proprietary/common/beats/framework/semc_audioeffectif.jar:system/framework/semc_audioeffectif.jar \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libaudio_init.so:system/lib/libaudio_init.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libAudioTrimmer.so:system/lib/libAudioTrimmer.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libbeatsbass.so:system/lib/libbeatsbass.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libbeatscorehtc.so:system/lib/libbeatscorehtc.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libbundlewrapper.so:system/lib/libbundlewrapper.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libreverbwrapper.so:system/lib/libreverbwrapper.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libSR_AudioIn.so:system/lib/libSR_AudioIn.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libsrsfx.so:system/lib/libsrsfx.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libvisualizer.so:system/lib/libvisualizer.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/libvoAudioFR.so:system/lib/libvoAudioFR.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/soundfx/libbeatsbass.so:system/lib/soundfx/libbeatsbass.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/soundfx/libcyanogen-dsp.so:system/lib/soundfx/libcyanogen-dsp.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/soundfx/libsrsfx.so:system/lib/soundfx/libsrsfx.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/soundfx/libxloudwrapper.so:system/lib/soundfx/libxloudwrapper.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/bluez-plugin/audio.so:system/lib/bluez-plugin/audio.so \
    vendor/Droid_Concepts/proprietary/common/beats/lib/hw/hwcomposer.msm8660.so:system/lib/hw/hwcomposer.msm8660.so \
    vendor/Droid_Concepts/proprietary/common/beats/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf
